# Generated by Django 4.1.13 on 2024-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='products/')),
                ('quantity', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('ratings', models.FloatField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='E_commerce.category')),
            ],
        ),
    ]
